server:
  port: 8080

spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

## Configuration Management uygulaması için

build:
  version: "1.0.0"

accounts:
  message: "Welcome to Account Service - DEFAULT"
  contactDetails:
    name: "EazyBank Support"
    email: "deneme@gmail.com"
  onCallSupport:
    -(555) 123-4567
    -(555) 987-6543
