server:
    port: 8081

spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.0.0"

accounts:
  message: "Welcome to EazyBank Account Service"
  contactDetails:
    name: "EazyBank Support"
    email: "deneme@gmail.com"
  onCallSupport:
    -(555) 123-4567
    -(555) 987-6543