server:
  port: 8080

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  application:
    name: account
  datasource:
    url: jdbc:h2:mem:accountdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

## Configuration Management uygulaması için

build:
  version: "1.0.0"

accounts:
  message: "Welcome to Account Service - DEFAULT"
  contactDetails:
    name: "EazyBank Support"
    email: "deneme@gmail.com"
  onCallSupport:
    -(555) 123-4567
    -(555) 987-6543
