server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:accountdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

## Configuration Management uygulaması için

build:
  version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"

accounts:
  message: "Welcome to Card Service - DEFAULT"
  contactDetails:
    name: "EazyBank Support"
    email: "deneme@gmail.com"
  onCallSupport:
    -(555) 123-4567
    -(555) 987-6543
