server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

## Configuration Management uygulaması için

build:
  version: "1.0.0"

info:
  app:
    name: "account"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

cards:
  message: "Welcome to Card Service - DEFAULT"
  contactDetails:
    name: "EazyBank Support"
    email: "deneme@gmail.com"
  onCallSupport:
    -(555) 123-4567
    -(555) 987-6543
